project:
  type: website
  output-dir: docs
  
website:
  title: "Dr. Francois Nguyen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - vision.qmd
      - philosophy.qmd
      - services.qmd
      - innovation.qmd
      - assessment.qmd
      - impact.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/drwin22/quartro
      - icon: youtube
        href: https://youtube.com/
      - icon: quatro
        href: https://github.com/drwin22/quartro
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, @ Dr. Francois Nguyen"

format:
  html:
    theme: superhero
    mainfont: Arial
    fontsize: 1.7rem
    toc: true

editor: source

