---
title: "Innovation"
---

## Teaching pedigogy
Innovative Teaching Strategies and Materials.

Francois Nguyen is a believer and early implementer of technology in the classroom. As early as the 1990s, Francois adopted computer technology to teach math using platforms such as PLATO and Math Enables. Even though these platforms were not well developed, they allowed students to work individually at their own pace which especially served limited English speaking students well. 

As technology grew, Francois was involved in the development of the ITC (Information Technology Center) which offered a computer lab for individual workers and a multimedia classroom for group instruction. Francois worked with colleague Bob Bilyk to implement many innovative teaching strategies.

## Online Learning
Francois was among the first to provide online classes to students in the early 2000s. His algebra classes allowed students to work at their own pace while also getting feedback and evaluations from him. The online class structure more easily accommodated differentiation and a more personalized learning approach.

Francois used the flipped classroom model early on. Students would prepare their materials before coming to class and use class time to come together with common questions. This method created a more nurturing and supportive environment where students felt safe to ask questions and learn from each other.

For students who were first generation college students, limited English proficient, or coming back to education after a long time, Francois’ classes were a place where students could get to know each other and work in groups so they could feel supported by their peers.

## Flexibility
Another innovation Francois developed and taught were the accelerated algebra classes which enabled students to complete an algebra course in half a semester saving time and money. This enabled students to more quickly enter into their major training program.

In 2020, Francois developed and taught an intermediate statistics class. This class attracted many students from college programs requiring statistics. It was a project based class where students had to use various programs for data analysis. This class emphasized real world examples such as analyzing COVID data and election results. After this class, students could further their study of data sciences inspiring them to continue in that high demand field.
